Elide enarx-keepldr argument
enarx-keepldr commit f0d9c7e39eb29d084be394d9a1c38b399ae15496
injects the enarx-keepldr image name into the process command line
arguments to the exec syscall in the event the nil backend is selected.

This accidentally pollutes the arguments list that enarx-wasmldr
passes to the workload run function, as enarx-wasmldr only skips 1
argument because it expects the first argument is simply the path
to the enarx-wasmldr image.

This patch updates the arg skipping logic to account for an
enarx-keepldr nil backend launch so we don't accidentally pollute
the arguments list passed to the workload run function and crash:

$ ENARX_BACKEND=nil 3<>demo.wasm ./enarx-keepldr exec enarx-wasmldr
thread 'main' panicked at 'Failed to run workload: IoError(Kind(InvalidInput))', src/main.rs:70:52
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Signed-off-by: Connor Kuehl <ckuehl@redhat.com>